version: "3"
services:
  pizza_app:
    build: ./App
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pizza_appapp_development
    command: -p 5434
    expose:
      - 5434
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
