version: "3"
services:
  pizza_app:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pizza_appapp_development
    command: -p 5433